AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  HelloFromWorkshop

  Sample SAM Template for HelloFromWorkshop

Parameters:
  DynamoDBIndexName:
    Type: String
    Default: MessageGSI

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    CodeUri: app/
    Handler: webhooks.lambda_handler
    Runtime: ruby3.2
    Architectures:
      - arm64
    Environment:
      Variables:
        API_TOKEN: 'api token'
        TELEGRAM_BOT_TOKEN: tg bot token
        DYNAMODB_TABLE: !Ref AmazingDB
        DYNAMODB_INDEX_NAME: !Ref DynamoDBIndexName

Resources:
  WebhooksFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionUrlConfig:
        AuthType: NONE
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: "Allow"
              Action:
                - dynamodb:PutItem
                - dynamodb:Query
              Resource: 
                - !GetAtt AmazingDB.Arn
                - !Sub "${AmazingDB.Arn}/index/*"
  AmazingDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "N"
        - AttributeName: "message"
          AttributeType: "S"
        - AttributeName: "timestamp"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "timestamp"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      LocalSecondaryIndexes:
        - IndexName: "TimestampLSI"
          KeySchema:
            - AttributeName: "id"
              KeyType: "HASH"
            - AttributeName: "timestamp"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      GlobalSecondaryIndexes:
        - IndexName: !Ref DynamoDBIndexName
          KeySchema:
            - AttributeName: "message"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
            

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  WebhooksUrl:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !GetAtt WebhooksFunctionUrl.FunctionUrl
